### ISSUE TITLE
ISSUE: Latest release of HA breaks Mail and Packages

### ISSUE THREAD

**Issue by ckhyatt** [moralmunky/Home-Assistant-Mail-And-Packages#1189]
**Describe the bug**
After updating to 26.2.2 The integration fails to load with errors in the logs below.

**Environment (please complete the following information)
 - OS: [e.g. HassOS/Raspbian/CentOS] HASSOS
 - Type of device: [e.g. RPi3/NUC/Synology] NUC
 - Home Assistant version: [e.g. 0.105.5] 26.2.2
 - Hassio/Docker/Core? 
 - Component version: [e.g. 0.1.2] Version 0.5.0-b0

**Logs**
026-02-17 21:08:13.611 INFO (MainThread) [custom_components.mail_and_packages] Version 0.5.0-b0 is starting, if you have any issues please report them here: http://github.com/moralmunky/Home-Assistant-Mail-And-Packages
2026-02-17 21:08:13.611 DEBUG (MainThread) [custom_components.mail_and_packages] Data will be update every 0:05:00
2026-02-17 21:08:13.614 DEBUG (MainThread) [custom_components.mail_and_packages.helpers] Starting process_emails function
2026-02-17 21:08:13.614 DEBUG (MainThread) [custom_components.mail_and_packages.helpers] Attempting to log in to IMAP server.
2026-02-17 21:08:13.621 ERROR (MainThread) [custom_components.mail_and_packages] Problem updating sensors: 'IMAP4' object has no attribute 'starttls'
2026-02-17 21:08:13.621 ERROR (MainThread) [custom_components.mail_and_packages] Error fetching Mail and Packages (192.168.2.178) data: 'IMAP4' object has no attribute 'starttls'
2026-02-17 21:08:13.621 DEBUG (MainThread) [custom_components.mail_and_packages] Finished fetching Mail and Packages (192.168.2.178) data in 0.007 seconds (success: False)
2026-02-17 21:08:13.621 ERROR (MainThread) [custom_components.mail_and_packages] Error updating sensor data: 'IMAP4' object has no attribute 'starttls'
2026-02-17 21:08:25.762 INFO (MainThread) [custom_components.mail_and_packages] Version 0.5.0-b0 is starting, if you have any issues please report them here: http://github.com/moralmunky/Home-Assistant-Mail-And-Packages
2026-02-17 21:08:25.762 DEBUG (MainThread) [custom_components.mail_and_packages] Data will be update every 0:05:00
2026-02-17 21:08:25.765 DEBUG (MainThread) [custom_components.mail_and_packages.helpers] Starting process_emails function
2026-02-17 21:08:25.765 DEBUG (MainThread) [custom_components.mail_and_packages.helpers] Attempting to log in to IMAP server.
2026-02-17 21:08:25.841 ERROR (MainThread) [custom_components.mail_and_packages] Problem updating sensors: 'IMAP4' object has no attribute 'starttls'
2026-02-17 21:08:25.841 ERROR (MainThread) [custom_components.mail_and_packages] Error fetching Mail and Packages (192.168.2.178) data: 'IMAP4' object has no attribute 'starttls'
2026-02-17 21:08:25.841 DEBUG (MainThread) [custom_components.mail_and_packages] Finished fetching Mail and Packages (192.168.2.178) data in 0.077 seconds (success: False)
2026-02-17 21:08:25.841 ERROR (MainThread) [custom_components.mail_and_packages] Error updating sensor data: 'IMAP4' object has no attribute 'starttls'

**Screenshots**

<img width="340" height="140" alt="Image" src="https://github.com/user-attachments/assets/501d8f77-6bfb-4b99-ba93-9c6e932d9bb2" />

**Additional context**
Please add emails in plain/text format if possible and applicable.

**Comment by firstof9** [comment]
Have you tried restarting Home Assistant already?

**Comment by ckhyatt** [comment]
Yes, reloading the integration and restarting HA several times.

**Comment by ckhyatt** [comment]
Before I updated to the latest pre-release it was a different set of sensors but the same errors.

**Comment by firstof9** [comment]
Which email service are you using?

**Comment by ckhyatt** [comment]
Proton Mail

**Comment by firstof9** [comment]
And verify SSL Cert is unchecked?

**Comment by ckhyatt** [comment]
Chris ***@***.***> wrote:﻿firstof9 left a comment (moralmunky/Home-Assistant-Mail-And-Packages#1189)
And verify SSL Cert is unchecked?

**Comment by ckhyatt** [comment]
I haven’t touched the config since I set it up ~8 months ago.

**Comment by firstof9** [comment]
If you recently updated to `0.5.0-b0` it seems the updated library doesn't support "STARTTLS" for some reason.
Does proton's mail bridge support a regular SSL connection for IMAP?

**Comment by ckhyatt** [comment]
I will check. I am running PM on Debian distro with Docker and a really nice PM client this guy created.

**Comment by ckhyatt** [comment]
It has run flawlessly since I set it up.

**Comment by firstof9** [comment]
Yes the older slower library for sure supports startTLS

**Comment by ckhyatt** [comment]
Should I down grade to an earlier version?

**Comment by firstof9** [comment]
At this time, sure the latest 0.4.x version will suit your needs

**Comment by ckhyatt** [comment]
I down graded to 4.7. As I previously noted that version also has the issue after upgrading to 26.2.2.

2026-02-18 22:17:23.559 INFO (MainThread) [custom_components.mail_and_packages] Version 0.4.7 is starting, if you have any issues please report them here: http://github.com/moralmunky/Home-Assistant-Mail-And-Packages
2026-02-18 22:17:23.559 DEBUG (MainThread) [custom_components.mail_and_packages] Data will be update every 0:05:00
2026-02-18 22:17:23.564 DEBUG (SyncWorker_1) [custom_components.mail_and_packages.helpers] Starting process_emails function
2026-02-18 22:17:23.641 ERROR (MainThread) [custom_components.mail_and_packages] Problem updating sensors: b'no such user'
2026-02-18 22:17:23.641 ERROR (MainThread) [custom_components.mail_and_packages] Error fetching Mail and Packages (192.168.2.178) data: b'no such user'
2026-02-18 22:17:23.641 DEBUG (MainThread) [custom_components.mail_and_packages] Finished fetching Mail and Packages (192.168.2.178) data in 0.080 seconds (success: False)
2026-02-18 22:17:23.641 ERROR (MainThread) [custom_components.mail_and_packages] Error updating sensor data: b'no such user'
2026-02-18 22:17:44.546 INFO (MainThread) [custom_components.mail_and_packages] Version 0.4.7 is starting, if you have any issues please report them here: http://github.com/moralmunky/Home-Assistant-Mail-And-Packages
2026-02-18 22:17:44.546 DEBUG (MainThread) [custom_components.mail_and_packages] Data will be update every 0:05:00
2026-02-18 22:17:44.549 DEBUG (SyncWorker_9) [custom_components.mail_and_packages.helpers] Starting process_emails function
2026-02-18 22:17:44.654 ERROR (MainThread) [custom_components.mail_and_packages] Problem updating sensors: b'too many login attempts'
2026-02-18 22:17:44.655 ERROR (MainThread) [custom_components.mail_and_packages] Error fetching Mail and Packages (192.168.2.178) data: b'too many login attempts'
2026-02-18 22:17:44.655 DEBUG (MainThread) [custom_components.mail_and_packages] Finished fetching Mail and Packages (192.168.2.178) data in 0.106 seconds (success: False)
2026-02-18 22:17:44.655 ERROR (MainThread) [custom_components.mail_and_packages] Error updating sensor data: b'too many login attempts'

**Comment by firstof9** [comment]
No that's a different error: `no such user` and a `too many login attempts`

Your bridge is rejecting your login.

**Comment by ckhyatt** [comment]
Strange that it started with 26.2.2 and a different error with the pre-release version.

**Comment by firstof9** [comment]
If you find a way to change the IMAP setting to SSL instead of STARTTLS in the proton mail bridge settings, the latest version will work properly.

**Comment by ckhyatt** [comment]
I will check that out and let you know. Thanks!
